name: Sitama
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: '>=3.3.3 <4.0.0'

dependencies:
    flutter:
        sdk: flutter

  # Flutter UI Packages
    cupertino_icons: any         # Ikon iOS untuk aplikasi Flutter
    flutter_svg: any             # Mendukung tampilan gambar SVG
    dropdown_button2: any        # Kustomisasi dropdown button untuk Flutter
    animated_gradient: any

  # State Management
    flutter_bloc: any            # Implementasi pattern BLoC untuk manajemen state
    provider: any                # Package untuk state management berbasis provider
    
  # Date and Time Formatting
    intl: any                     # Format tanggal, waktu, dan internasionalisasi
  
  # Networking and APIs
    dio: any                     # HTTP client untuk komunikasi API yang efisien
    get_it: any                  # Service locator untuk dependency injection

  # Functional Programming and Utilities
    dartz: any                   # Menyediakan tipe data functional seperti `Either`, `Option`
    equatable: any               # Membantu untuk membandingkan objek tanpa overriding `==`
    logger: any                  # Logging utility untuk debug

  # Local Storage and Preferences
    shared_preferences: any      # Menyimpan data kecil secara lokal, seperti preferensi pengguna

  # File Management
    file_picker: any             # Memungkinkan pemilihan file dari perangkat
    path_provider: any
    permission_handler: any
    open_file: any
    
  # UI Components
    syncfusion_flutter_pdfviewer: any # PDF viewer untuk menampilkan file PDF dalam aplikasi
    pull_to_refresh: any          # Menambahkan fitur pull-to-refresh pada halaman list

  # Notifications
    flutter_local_notifications: any # Menampilkan notifikasi lokal pada perangkat

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^5.0.0

    flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  remove_alpha_ios: true
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 23
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true

    # To add assets to your application, add an assets section, like this:
    assets:
        - assets/images/
        - assets/vectors/

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
