name: Sitama
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: '>=3.3.3 <4.0.0'

dependencies:
    flutter:
        sdk: flutter

  # Flutter UI Packages
    cupertino_icons: any         # Ikon iOS untuk aplikasi Flutter
    flutter_svg: any             # Mendukung tampilan gambar SVG
    dropdown_button2: any        # Kustomisasi dropdown button untuk Flutter
    animated_gradient: any

  # State Management
    flutter_bloc: any            # Implementasi pattern BLoC untuk manajemen state
    provider: any                # Package untuk state management berbasis provider
    
  # Date and Time Formatting
    intl: any                     # Format tanggal, waktu, dan internasionalisasi
  
  # Networking and APIs
    dio: any                     # HTTP client untuk komunikasi API yang efisien
    get_it: any                  # Service locator untuk dependency injection
    connectivity_plus: ^6.1.1    # Mendukung pengecekan koneksi internet
    fluttertoast: ^8.0.8         # Menampilkan toast notifikasi

  # Functional Programming and Utilities
    dartz: any                   # Menyediakan tipe data functional seperti `Either`, `Option`
    equatable: any               # Membantu untuk membandingkan objek tanpa overriding `==`
    logger: any                  # Logging utility untuk debug

  # Local Storage and Preferences
    shared_preferences: any      # Menyimpan data kecil secara lokal, seperti preferensi pengguna

  # File Management
    file_picker: any             # Memungkinkan pemilihan file dari perangkat
    path_provider: any           # Menyediakan akses ke direktori sistem
    path: any
    permission_handler: any      # Mengelola izin aplikasi
    open_file: any               # Membuka file dari perangkat
    
  # UI Components
    syncfusion_flutter_pdfviewer: any # PDF viewer untuk menampilkan file PDF dalam aplikasi
    pull_to_refresh: any          # Menambahkan fitur pull-to-refresh pada halaman list

  # Notifications
    flutter_local_notifications: any # Menampilkan notifikasi lokal pada perangkat

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^5.0.0

    flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  remove_alpha_ios: true
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 23
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

flutter:
    uses-material-design: true
    assets:
        - assets/images/
        - assets/vectors/
